export const userPermissions = {
  admin: {
    canViewAll: true,
    canManageCustomers: true,
    canManageVehicles: true,
    canManageServices: true,
    canManagePayments: true,
    canViewReports: true,
    canViewIndividualReports: true,
    canManageUsers: true,
    canDelete: true,
    canEditPayments: true,
    canViewAllVehicles: true,
    canViewAllCustomers: true,
    canGenerateReports: true,
    canViewRevenueReport: true, // إضافة صلاحية جديدة
  },
  user: {
    canViewAll: true,
    canManageCustomers: false,
    canManageVehicles: false,
    canManageServices: true,
    canManagePayments: false,
    canViewReports: false,
    canViewIndividualReports: true,
    canManageUsers: false,
    canDelete: false,
    canEditPayments: false,
    canViewAllVehicles: true,
    canViewAllCustomers: true,
    canGenerateReports: false,
    canViewRevenueReport: false,
  },
  technician: {
    canViewAll: true,
    canManageCustomers: false,
    canManageVehicles: false,
    canManageServices: true,
    canManagePayments: true,
    canViewReports: false,
    canViewIndividualReports: true,
    canManageUsers: false,
    canDelete: false,
    canEditPayments: false,
    canViewAllVehicles: true,
    canViewAllCustomers: true,
    canGenerateReports: false,
    canViewRevenueReport: false,
  },
  customer: {
    canViewAll: false,
    canManageCustomers: false,
    canManageVehicles: false,
    canManageServices: false,
    canManagePayments: false,
    canViewReports: true,
    canManageUsers: false,
    canDelete: false,
    canEditPayments: false,
    canViewAllVehicles: true,
    canViewAllCustomers: false,
    canGenerateReports: true,
    canAdd: false,
    canEdit: false,
    canViewRevenueReport: false, // منع الإذن
  }
};